Update requirements.txt
Changed uWSGI==2.0.12 to WSGI==2.0.13 because on Ubuntu 17.04 (4.10.0-21-generic/gcc-6) installing the requirements gives a compiling error.

Error:
*** uWSGI compiling server core ***

[thread 0][x86_64-linux-gnu-gcc -pthread] plugins/http/http.o
plugins/corerouter/cr_map.c: In function ‘uwsgi_cr_map_use_static_nodes’:
plugins/corerouter/cr_map.c:156:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if (!next_node)
     ^~
plugins/corerouter/cr_map.c:159:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
      while (tmp_node != next_node) {
      ^~~~~
[thread 4][x86_64-linux-gnu-gcc -pthread] plugins/http/keepalive.o
cc1: all warnings being treated as errors